services:
  app:
    image: diplom_design_hope_deploy_20f9eb3_vm-app
    container_name: diplom_app
    restart: always
    ports:
      - "3000:3000"
    entrypoint: ["/app/docker-entrypoint.sh"]
    volumes:
      - ../Diplom_Design_Hope_deploy_20f9eb3_vm/public/uploads:/app/public/uploads
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/diplom_design_hope
      SESSION_SECRET: change_me_please_replace_with_32_char_secret
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    container_name: diplom_postgres
    restart: always
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diplom_design_hope
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d diplom_design_hope"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
